### ISSUE TITLE
Base HTML recovery 

### ISSUE THREAD

**Issue by pratt0007** [NITRR-Open-Source-Community/CRM#7]
There are some issues with Base.HTML file.
Resolve those issues.

**Comment by tanishk2705** [comment]
I would like to work on this issue please assign this issue to me.

**Comment by pratt0007** [comment]
Yeah Sure!!

**Comment by Bhawna003** [comment]
Please assign this problem to me.

**Comment by VasuBhakt** [comment]
Please assign this problem to me
